### ISSUE TITLE
Twitch toolkit Enhancements

### ISSUE THREAD

**Issue by godofdream** [pardeike/Puppeteer#2]
I really like the puppeteer Project, and I would like to help with some Parts I would like to add Server side.

Basicly the twitch toolkit mods are really nice but they lack some functions, that can be better represented on a website.
Additionally it would reduce the spam of twitch commands.

Available with or without a pawn
- [ ] Modlist
- [ ] Purchaselist
  - [ ] showing Price
  - [ ] showing karma
  - [ ] showing stats of an buyable Item

Available with a pawn
- [ ] possible Surgeries and their Price
  - [ ] stats of possible surgeries
- [ ] buyable traits
  - [ ] stats & description of the buyable traits

**Comment by pardeike** [comment]
basic integration with auto complete is now implemented
