### ISSUE TITLE
Unintentionally Awarding Toolkit Coins

### ISSUE THREAD

**Issue by SirRandoo** [pardeike/Puppeteer#5]
Currently Puppeteer's Twitch Toolkit integration calls `Viewers.AwardViewersCoins` as a means of refreshing Toolkit's viewer list, but Toolkit defaults to awarding coins when the value isn't above 0. As it stands currently, that method is called every time a viewer joins Puppeteer, so every join would give every viewer currently in Toolkit's viewer list extra coins.

If you'd want to manually obtain the viewer list while the game isn't running, you'd have to get the current list of viewers from the [chatters](https://discuss.dev.twitch.tv/t/get-current-viewer-usernames/872/3) api, then stores it inside the `jsonallviewers` [static field](https://github.com/hodldeeznuts/twitchtoolkit/blob/552a388fd71b663fbb35638eb78e8acb30121e3c/TwitchToolkit/Viewers.cs#L15) in the `Viewers` class.

**Comment by pardeike** [comment]
I don’t need the viewers list. I call this method only because not calling it will cause an error when a newly joined twitch viewer interacts with chat commands via the puppeteer website instead of using twitch chat. The purpose of calling the method is purely to make Toolkit load and store the viewer so when I fake send the chat to toolkit it has seen the sender.

**Comment by pardeike** [comment]
I should instead use [this method](https://github.com/hodldeeznuts/twitchtoolkit/blob/9efb42313a62f09c7ee07897a50beccc5ba96d4d/TwitchToolkit/Viewers.cs#L207) instead.

**Comment by SirRandoo** [comment]
If all you want is to insert a Puppeteer viewer inside of Toolkit's viewer cache, you could use [GetViewer](https://github.com/hodldeeznuts/twitchtoolkit/blob/9efb42313a62f09c7ee07897a50beccc5ba96d4d/TwitchToolkit/Viewers.cs#L262), or construct a new [Viewer](https://github.com/hodldeeznuts/twitchtoolkit/blob/9efb42313a62f09c7ee07897a50beccc5ba96d4d/TwitchToolkit/Viewer.cs#L21). Either option would mimic the results you're getting from the currently used method without the coin side effect.
